current_version = "0.3.0"

[[files]]
path = "Cargo.toml"
search = "version = \"{{current_version}}\""
replace = "version = \"{{new_version}}\""

[[files]]
path = "pyproject.toml"
search = "version = \"{{current_version}}\""
replace = "version = \"{{new_version}}\""

[[files]]
path = "CHANGELOG.md"
search = "# Changelog"
replace = """
# Changelog

## v{{new_version}} - {{now|date}} (JST)
"""
