current_version = "0.2.0"

[[files]]
path = "Cargo.toml"
search = "version = \"{{current_version}}\""
replace = "version = \"{{new_version}}\""

[[files]]
path = "src/main.rs"
search = "const VERSION: &'static str = \"{{current_version}}\";"
replace = "const VERSION: &'static str = \"{{new_version}}\";"
