name: 'Deployment document'

on:
  workflow_call:
  workflow_dispatch:

jobs:
  deploy-doc:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version-file: '.python-version'
      - name: Configure venv
        run: |
          pip install uv
          uv venv
          uv pip install -r requirements.lock
      - name: Run tests
        run: |
          source .venv/bin/activate
          make -C doc dirhtml
      - name: Publish
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy doc/_build/dirhtml --project-name=${{ secrets.CLOUDFLARE_PAGES_NAME }} --branch=main
