name: 'CI jobs'

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v4'
      - uses: 'Swatinem/rust-cache@v2'
      - name: 'Run formatter'
        run: cargo fmt --all --check
      - name: 'Run linter'
        run: cargo clippy --workspace --all-targets --all-features --locked
  test:
    needs: ['lint']
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v4'
      - uses: 'Swatinem/rust-cache@v2'
      - name: 'Run test'
        run: cargo test --verbose

